### ISSUE TITLE
Setup SpecFlow meta packages in Corvus.Testing

### ISSUE THREAD

**Issue by JamesDawson** [endjin/Endjin.MetaPackage.SpecFlow#1]
We need:

- [x] dummy project that references the SpecFlow dependencies for the standard NUnit scenario
- [x] dummy project that references the SpecFlow dependencies for the Azure Functions NUnit scenario
- [x] update project references
- [x] integrate pr-autoflow in Corvus.Testing solution

**Comment by JamesDawson** [comment]
pr-autoflow now updated and this has been released in Corvus.Testing v1.0.1
